
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ankitkachru.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /ankitkachru.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-77528324-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Ankit Kachroo"
title: "{ Ankit Kachroo }"
description: "You've reached the website of Ankit Kachroo."
keywords: "ankit, kachroo, ankitkachru, kachru, ankitkachroo, software, ML, AI, engineering, BITS, pilani, mesra,premier, gardware, genius, kashmiri, computer, hard, working, food, adobe, quant, quantitative, research, finance, worldquant, alpha, virtual, reality, simulation, NLP, language, google, author, blog, server, systems, product, manager, program, de, shaw, placement, coordinator, rapidbizapps, rapid, biz, apps, mts, intern, quality, assurance, facebook, linkedin, enthusiast, ui, ux, pattern, recognition, soft, computing, genetic, algorithms, hackerrank, hackerearth, data, structures, C++, C#, C, java, javascript, nodejs, salesforce, xray, vision, computer, aws, app, engine, android, ios, sql, database, administrator, php, prolog, cloud, machine learning, bit, mesra, artificial, intelligence, python, cse, computer, science, code, ankitkachroo, birla, institute, technology, AI"
favicon: "/img/favicon.png"

################
# Header layout #
################

black-favicon: "/img/favicon.png"

background-img: "/img/intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 500
lines: # You can add HTML Tags in the Text
  - text: "I like to code."
  - text: "I like to create."
  - text: "I like to design."
  - text: "I like to develop."
  - text: "I like to play."
  - text: "I like to write."

me-img: "/img/ava.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: true

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "ankitkachru"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/sap.png"
    date: "July 2017 - Present"
    description: "Developer @ <a href=\"https://www.sap.com\" target=\"_blank\">SAP Labs</a>"
  - image: "/img/timeline/rba.png"
    date: "May 2016 - July 2016"
    description: "MTS-Intern @ <a href=\"http://rapidbizapps.com\" target=\"_blank\">rapidBizApps Pvt. Ltd.</a>"
  - image: "/img/timeline/ecell.jpg"
    date: "July 2015 - Apr 2017"
    description: "Head Coordinator @ <a href=\"http://ecellbitj.tk\" target=\"_blank\">Entrepreneurship Cell, BIT</a>"
  - image: "/img/timeline/gounesco.png"
    date: "January 2015 - July 2015"
    description: "Campus Ambassador @ <a href=\"http://gounesco.com\" target=\"_blank\">GoUNESCO</a>"
  - image: "/img/timeline/bitlogo.png"
    date: "2013-2017"
    description: "Bachelor of Engineering @ <a href=\"http://bitmesra.ac.in\" target=\"_blank\">Birla Institute of Technology, Mesra, Ranchi</a> in Computer Science"
  - image: "/img/timeline/dps_logo.jpg"
    date: "1998-2013"
    description: "Student @ <a href=\"http://dpsjammu.in\" target=\"_blank\">Delhi Public School, Jammu</a>"

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "Curriculum Vitæ "

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Ankit Kachroo is an awesome person. He works on computer science projects. In his spare time, Ankit likes to eat :p."
author_blurb_image: "/img/default.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/ankitkachru"
  - title: "github"
    url: "https://github.com/ankitkachru"
  - title: "linkedin"
    url: "https://linkedin.com/in/ankitkachru"
  - title: "envelope"
    url: "mailto:kachruankit@gmail.com"


############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
 # Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
